config/routes.rb
Rails.application.routes.draw do
  get 'cooks/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'meals#index'

  resources :meals, only: [ :index, :show, :new, :create ] do
    resources :orders, only: :create
    collection do
      get 'category'
    end
  end

  resources :orders, only: [ :show ]

  resources :dashboards, only: [ :index, :update ]

  resources :cooks, only: [ :show ]

  namespace :admin do
    resources :meals, only: [:index]
    resources :orders, only: [:index, :update]
    resources :daily_meal, only: [ :show ]
  end

  patch '/orders/:id/review_save', to: 'orders#review_save', as:'review_save'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < User
  has_many :meals, dependent: :destroy
  belongs_to :daily_meal, class_name: 'Meal', required: false

  def orders_reviews
   meals.map(&:orders).flatten
  end

  def average_rating
    counter = 0
    meals = Meal.where(cook_id: self)
    order_count = 0

    meals.each do |meal|
      order_count += meal.orders.count
      rated_orders = meal.orders
      rated_orders.each do |order|
        counter += order.rating
      end
    end

    if counter.zero?
      average_rating = 0
    else
      average_rating = (counter / order_count).to_i
    end
    average_rating
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :cook
  has_many :orders

  validates :category, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 300 }
  validates :price, presence: true
  validates :quantity, presence: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/order.rb
  class Order < ApplicationRecord
  belongs_to :meal
  belongs_to :user
  validates :time, presence: true

  scope :rated, -> { where.not(rating: nil)}

  def available_quantities
    # TODO return the real available quantity based on the stock
    (1..8)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/admin/daily_meals_controller.rb
class Admin::DailyMealsController < ApplicationController
  def show
    @meal = Meal.find(params[:meal_id])
    @user = current_user
    @user.daily_meal = @meal
  end
end

app/controllers/admin/meals_controller.rb
class Admin::MealsController < ApplicationController
  def index
    @meals = Meal.where(cook_id: current_user)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @daily_meal = current_user.daily_meal_id
    @cook_orders = @daily_meal.orders
    @orders = @cook_orders.sort_by(:completed)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order.save
    redirect_to dashboards_path
  end

  private

  def order_params
    params.require(:order).permit(:time, :quantity, :completed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :store_user_location!, if: :storable_location?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :type, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?


  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  def show
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @orders = policy_scope(Order).all
    @meals = policy_scope(Meal).all
    @new_orders = new_orders
    @complete_orders = complete_orders
  end

  def update
    @user = current_user

    if meal_id.zero?
      @user.daily_meal = nil
    else
      @meal = Meal.find(params[:cook][:daily_meal].to_i)
      @user.daily_meal = @meal
    end

    authorize @user
    @user.save
    redirect_to dashboards_path
  end

  private

  def meal_id
    params[:cook][:daily_meal].to_i
  end

  def new_orders
    @daily_meal = current_user.daily_meal_id
    if @daily_meal.nil?
      @new_orders = []
    else
      @meal = Meal.find(@daily_meal.to_i)
      @new_orders = @meal.orders.where(completed: false)
    end
    @new_orders
  end

  def complete_orders
    @daily_meal = current_user.daily_meal_id
    if @daily_meal.nil?
      @complete_orders = []
    else
      @meal = Meal.find(@daily_meal.to_i)
      @complete_orders = @meal.orders.where(completed: true)
    end
    @complete_orders
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show, :category ]

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    authorize @meal
    @order = @meal.orders.new
    @orders_reviews = Order.joins(:user).where(meal_id: @meal.id).limit(5)
    @cooks = Cook.geocoded
    @cook = @meal.cook
    @marker = {
      lat: @cook.latitude,
      lng: @cook.longitude
    }
  end

  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.cook = current_user
    authorize @meal

    if @meal.save
      @meal.cook.daily_meal = @meal
      @meal.cook.save
      redirect_to meals_path
    else
      render :new
    end
  end

  def category
    @parameter = params[:search].capitalize
    @results = Meal.where(category: @parameter)

    authorize :meal, @meal
  end

  private

  def meal_params
    params.require(:meal).permit(:category, :title, :description, :price,
                                 :quantity, :photo, :cook)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = policy_scope(Order).all
  end

  def show
    @order = Order.find(params[:id])
    @meal = @order.meal
    @cooks = Cook.geocoded
    @cook = @meal.cook
    @marker = {
      lat: @cook.latitude,
      lng: @cook.longitude
    }

    authorize @order
  end

  def create
    @meal = Meal.find(params[:meal_id])
    @order = @meal.orders.new(order_params)
    @order.user = current_user
    authorize @order
    @order.save
    redirect_to order_path(@order)
  end

  def review_save
    @order = Order.find(params[:id])
    @order.rating = params[:order][:rating]
    @order.review = params[:order][:review]
    authorize @order
    @order.save
    redirect_to order_path
  end

  private

  def order_params
    params.require(:order).permit(:time, :quantity, :rating, :review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/meals/_index.html.erb
<%= simple_form_for user, url: dashboard_path(user) do |f| %>
    <div class="form-group mt-3" id="search-meals">
      <%= f.input :daily_meal, label: false, collection: Meal.where(cook_id: user), include_blank: true%>
    </div>
    <div class="m-3 text-center">
      <%= f.submit 'Update', class: "btn btn-success"%>
    </div>
<% end %>

<%= button_to "+ New Meal", new_meal_path, class: "btn btn-success", :method => "get" %>

app/views/admin/orders/_index.html.erb
<% @daily_meal = current_user.daily_meal_id %>

<% if @daily_meal.nil? %>
  <p>No orders.</p>
<% else %>
  <% @meal = Meal.find(@daily_meal.to_i) %>
  <% @cook_orders = @meal.orders %>
  <% @orders = @cook_orders.sort_by { |order| order.time } %>

  <% @orders.each do |order| %>
    <div class="d-flex justify-content-around mb-3">
      <%= image_tag (order.user.photo), class: "avatar mt-2" %>
      <div class="card" style="width: 70%;">
        <div class="d-flex justify-content-between pb-0">
          <div class="text-left p-2 mt-1" style="height: auto; font-size: 12px;">
            <p><strong><%= order.user.first_name %> <%= order.user.last_name %></strong>
            <br>Pick Up Time: <%= order.time.strftime('%H:%M %p') %>
            <br>Order: <%= order.meal.title %> x <%= order.quantity %>
            <br>Total: EUR €<%= order.meal.price * order.quantity %></p>
          </div>
          <div class="complete mr-4 mt-1">
            <% if order.completed %>
              <div class="mt-3">
                <%= button_tag "Completed", class: "btn btn-success btn-sm my-2 my-sm-0" %>
              </div>
            <% else %>
              <%= render "admin/orders/update", order: order %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/orders/_update.html.erb
<%= form_for(order, url: admin_order_path(order)) do |f| %>
  <div>
    <%= f.check_box :completed %>
  </div>
  <%= f.submit "Complete", class: "btn btn-outline-success btn-sm my-2 my-sm-0" %>
<% end %>

app/views/cooks/show.html.erb
<h1>Cooks#show</h1>
<p>Find me in app/views/cooks/show.html.erb</p>
<p><%= current_user.daily_meal %></p>

app/views/dashboards/index.html.erb
<div class="container">
  <h1 class="navbar-brand" style="font-size: 30px;"><%= current_user.first_name %>'s Dashboard</h1>
  <p><%= Date.today.to_formatted_s(:long) %></p>

  <div class="container">

    <div class="row">


      <div class="col-4">
      <! --- Profile bar ---->
        <div class="card-prof-bar p-3 mt-3 mb-3">

          <! --- Header ---->
          <div class="cards-prof-bar">
            <%= image_tag (current_user.photo), class: "avatar-dashboard" %>
            <div class="card-profile">
              <p class="mb-1"><strong><%= current_user.first_name %> <%= current_user.last_name %></strong></p>
              <p>
                <% current_user.average_rating.times do %>
                  <i class="fas fa-star" style="font-size: 18px; color: yellow;"></i>
                <% end %>
              </p>
            </div>
          </div>

          <! --- Order cards ---->
          <div class="cards-prof-bar">
            <div class="card-prof-bar">
              <i class="far fa-file-alt"></i>
              <h3><%= @new_orders.length %></h3>
              <p>New Orders</p>
            </div>
            <div class="card-prof-bar ml-2">
              <i class="fas fa-file-alt"></i>
              <h3><%= @complete_orders.length %></h3>
              <p>Complete Orders</p>
            </div>
          </div>

          <! --- About  ---->
          <div class="card-about">
            <p><strong>About Me</strong></p>
            <p>Hi, I'm <%= current_user.first_name %>. I've been cooking all my life, and it's a real passion of mine. I'm excited to share my favorite reciptes with you all!</p>
            <p><strong>Address</strong></p>
            <p><%= current_user.address %></p>
          </div>
        </div>
      </div>


      <div class="col-8">
      <! --- Meal & orders section ---->
        <div class="card-dash p-3 mt-3 mb-3">

          <div class="card p-2 mb-3 text-center">

            <h3 class="navbar-brand" style="font-size: 32px;">MY MEAL OF THE DAY</h3>

            <div class="d-flex justify-space-around">
              <% if current_user.daily_meal.nil? %>
                <div class="card text-center p-3 mr-2" style="width: 500px;"><br><br>
                  <p>[Please set your meal of the day]</p>
                </div>
              <% else %>
                <div><%= render 'components/dashboard_card', meals: [current_user.daily_meal] %></div>
              <% end %>
              <div class="pt-5" style="width: 900px;"><%= render "admin/meals/index", user: current_user %></div>
            </div>
            <br><br>
            <h4 class="text-left navbar-brand" style="font-size: 20px;">TODAY'S ORDERS</h4>
            <div class="card p-3 mb-3 text-center">
              <%= render "admin/orders/index" %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'components/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <footer>
  <%= render 'components/footer' %>
  </footer>
</html>

app/views/meals/_call_to_authenticate.html.erb
<%= link_to "Sign in to order", new_user_session_path(return_to: meal_path(@meal)) %>

app/views/meals/_confirmation_popup.html.erb
         <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <strong> Order Confirmation </strong>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                </button>
              </div>
              <div class="modal-body">
              </div>
              <div class="modal-footer" style="border: none">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button class="btn btn-success" data-toggle="modal" data-target="#myNewModal">Yes</button>
                <%# link_to "Yes", order_path(@order) %>
              </div>
            </div>
          </div>
        </div>

app/views/meals/_form.html.erb
<div class="container">
  <%= simple_form_for [@meal, @order] do |f| %>
    <div class="form-group">
      <%= f.input :quantity, collection: @order.available_quantities, include_blank: false%>
      <%= f.input :time, collection: [['19h-20h', '19:00'], ['20h-21h', '20:00'], ['21h-22h', '21:00']], include_blank: false%>
    </div>
    <div class="centered">
      <%= f.submit class: "btn btn-success mt-1 mb-1", data: {toggle: "modal", target: "#myModal"} %>
    </div>
  <% end %>

</div>

app/views/meals/_info_window.html.erb
<h2><%= @cook.name %></h2>
<p><%= @cook.address %></p>

app/views/meals/category.html.erb
<div class="container d-flex justify-content-center">
  <div class="cards-container">
    <% if @results.length == 0 %>
      <br><h4> 😩 There are no <%= @parameter.capitalize %> meals today. Try another search!</h4>
      <h4> </h4>
    <% else %>
      <div>
        <h2><%= @parameter.capitalize %> meals near you</h2><br>
      </div>
      <%= render 'components/main_cards', meals: @results %>
    <% end %>
  </div>
</div>

app/views/meals/index.html.erb
<div class="container d-flex justify-content-center">
  <div class="cards-container">
    <h2 class="cards-title"> What are you in the mood for?</h2>
    <div class="cards">
      <%= link_to "/meals/category?utf8=✓&search=Japanese", class: 'category-link' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1534482421-64566f976cfa?ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80)">
          Japanese
        </div>
      <% end %>

      <%= link_to "/meals/category?utf8=✓&search=Italian", class: 'category-link' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1518675219903-c682c4b16b1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80)">
          Italian
        </div>
      <% end %>

      <%= link_to "/meals/category?utf8=✓&search=Veggies", class: 'category-link' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1464226184884-fa280b87c399?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
          Veggies
        </div>
      <% end %>

      <%= link_to "/meals/category?utf8=✓&search=Pastries", class: 'category-link' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1491185474061-a1dad922eeab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
          Pastries
        </div>
      <% end %>
    </div>
    <br>
    <br>
      <div><h2 class="cards-title"> Meals of the day around you</h2></div>
      <%= render 'components/main_cards', meals: @meals %>
  </div>
</div>

app/views/meals/new.html.erb
<div class="container">
  <h1> Add a new meal</h1>
  <%= simple_form_for @meal do |f| %>
  <%= f.input :category %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :quantity %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add your new meal", class: "btn btn-primary" %>
<% end %>
</div>

app/views/meals/show.html.erb
<div class="container">
    <div>
      <h2><%= @meal.title %> | <%= @meal.category %></h2>
    </div>

    <div class="main-banner">
      <div class="chef-banner">
        <img src="<%= @meal.cook.photo %>" class="card-trip-user avatar-bordered" />
      </div>
        <div class="chef-reviews">
        <% @cook.average_rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <div>
          <% if @orders_reviews.count == 0%>
            <p>0 review</p>
            <% else %>
            <p><%= @orders_reviews.count %> reviews</p>
          <% end %>
        </div>
        <br />
      </div>
        <p style="text-align: center;"> Chef <%= @cook.first_name %> <strong><%= @cook.last_name %></strong> is glad to present you the meal of the day : </p>
          <p style="font-style: italic; text-align: center;"><%= @meal.description %></p>
    </div>


    <div class="card-meal" style="background-image: url(<%= @meal.photo %>);">
      <div class="meal-order">
          <div class="border-bottom"> <p><strong>EUR <%= @meal.price %></strong></p>
          </div>
            <div class="order-form">
              <%= render("form") %>
            </div>
      </div>
    </div>

      <div class="reviews-banner">
        <% if @orders_reviews.length > 0 %>
          <% @orders_reviews.each do |order| %>
            <% if order.rating == nil %>

            <% else %>
              <div class="review">
              <div class="chef-banner-photo" style="display: flex">
                <img src="<%= order.user.photo %>" class="card-trip-user avatar-bordered" />
                <div class="chef-reviews-rating">
                  <% order.rating.to_i.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <div>
                    <p id="order-review"><%= order.review %></p>
                  </div>
                </div>
              </div>
            </div>
              <% end %>
            <% end %>
          <% else %>
            <div><p>There is no review yet 😥</p></div>
        <% end %>
      </div>

    <br>
    <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-marker="<%= @marker.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

<%= render 'confirmation_popup' %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/review.html.erb
<div class="container">
  <div class="main-banner">
    <h2> <%= @meal.title %></h2>
      <div class="chef-banner">
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        <br>
      <i class="fas fa-star"></i>
      </div>
  </div>

    <div class="card-meal">
      <div class="meal-order">
          <div class="border-bottom"> <p><%= @meal.description %> | <%= @meal.category %></p>
          </div>
            <div class="order-form">
              <%= render(current_user ? "form" : "call_to_authenticate") %>
            </div>
      </div>
    </div>

    <div class="card-product-other-meals">
      <h3>Other chef's meals</h3>
        <div class="cards">
          <div class="card-other-meals">
            <img src="https://images.unsplash.com/photo-1468777675496-5782faaea55b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80" />
            <p>Name of the meal</p>
          </div>
        </div>
    </div>
</div>

app/views/orders/show.html.erb
<div class="container justify-content-center">
  <div class="card text-center">
    <div class="card-header">
      <strong>Your order is complete!   🥳</strong>
    </div>
    <div class="card-body">
      <h5 class="card-title">ORDER SUMMARY</h5><br>
      <p class="card-text"><strong>PICK UP TIME:</strong><br><%= @order.time.strftime('%H:%M %p') %></p><br>
      <p class="card-text"><strong>YOUR MEAL OF THE DAY:</strong><br>
        <%= @order.meal.title %> x <%= @order.quantity %>
      </p>
      <p class="card-text"><strong>TOTAL:</strong><br>
        EUR <%= @order.quantity * @order.meal.price %>
      </p>
    </div>

    <% if @order.review == nil %>
    <div class="card-footer text-muted">
      And don't forget to leave a review !
    </div>
    <%= simple_form_for @order, url: review_save_path do |f| %>
    <%= f.input :rating, collection: 1..5, selected: 5 %>
    <%= f.input :review %>
    <%= f.submit "add a review", class: "btn btn-flat" %>
    <% end %>
    <br><br>
    <% else %>
    <div class="card-footer text-muted">
      <img src="https://media.giphy.com/media/3osxYdXvsGw6wT5lIY/giphy.gif">
    </div>
    <% end  %>
    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-marker="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
<script type="text/javascript">
  $j("<%= "#stars-wrapper" << @order.id.to_s %>").stars({
    callback: function(value, link){
      document.getElementById("starbutton").click();
    }
  });
</script>

app/views/pages/_confirmation_popup.html.erb
        <button type="button" class="btn btn-success btn-sml btn-tall btn-circle" data-toggle="modal" data-target="#myModal" style="font-size: 30px">Buy</button>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <strong> Order Confirmation </strong>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                </button>
              </div>
              <div class="modal-body">
                  Please confirm that your order #xxxxxxxx will be picked up at #time
              </div>
              <div class="modal-footer" style="border: none">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button class="btn btn-success" data-toggle="modal" data-target="#myNewModal" >Yes</button>
              </div>
            </div>
          </div>
        </div>

       <div class="modal fade" id="myNewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <strong> Order Confirmed</strong>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                </button>
              </div>
              <div class="modal-body">

              </div>
            </div>
          </div>
        </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1> How was your meal Today? </h1>
<div id="full-stars-example-two">
    <div class="rating-group">
        <input disabled checked class="rating__input rating__input--none" name="rating3" id="rating3-none" value="0" type="radio">
        <label aria-label="1 star" class="rating__label" for="rating3-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
        <input class="rating__input" name="rating3" id="rating3-1" value="1" type="radio">
        <label aria-label="2 stars" class="rating__label" for="rating3-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
        <input class="rating__input" name="rating3" id="rating3-2" value="2" type="radio">
        <label aria-label="3 stars" class="rating__label" for="rating3-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
        <input class="rating__input" name="rating3" id="rating3-3" value="3" type="radio">
        <label aria-label="4 stars" class="rating__label" for="rating3-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
        <input class="rating__input" name="rating3" id="rating3-4" value="4" type="radio">
        <label aria-label="5 stars" class="rating__label" for="rating3-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
        <input class="rating__input" name="rating3" id="rating3-5" value="5" type="radio">
          <br>
          <br>
    </div>

<form>

  <input type="text" id="textboxid">
  <br>
  <br>
<a class="btn btn-flat" href="#">Review</a>
</form>